### ISSUE TITLE
请求更新docker构建

### ISSUE THREAD

**Issue by lzw-723** [wushuo894/ani-rss#1]
![image](https://github.com/user-attachments/assets/ed20fec6-0308-42cb-947c-fa1ea7ec1544)

docker hub里默认的[openjdk基础镜像](https://hub.docker.com/_/openjdk)已经被弃用了，
更换`openjdk:11-jdk`到`eclipse-temurin:11-jre`可以保持更新还可以减小镜像体积 (200MB -> 80MB)。

**Comment by lzw-723** [comment]
另外README里可以添加Docker Compose部署方式

---

## Docker Compose部署

创建docker-compose.yml文件，内容如下

```yaml
version: "3"
services:
    ani-rss:
        container_name: ani-rss
        volumes:
            - /volume1/docker/ani-rss/config:/config
        ports:
            - 7789:7789
        environment:
            - PORT=7789
            - CONFIG=/config
            - TZ=Asia/Shanghai
        restart: always
        image: wushuo894/ani-rss
```

启动容器

```shell
docker compose up -d
```
