### ISSUE TITLE
放着一段时间没管，最近一看，日志已经开始报错了

### ISSUE THREAD

**Issue by w-66** [wushuo894/ani-rss#101]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [X] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [ ] 群晖套件

### 程序版本

v1.1.202 

### 问题描述

我更新了镜像，删除了所有，订阅，清除所有缓存，但是依然有此报错。在一周多之前，还是正常的。

### 日志

> [logs.zip](https://github.com/user-attachments/files/17936105/logs.zip)

具体报错如下
```
qb_ani-rss      | 2024-11-27 22:47:14 ERROR ani.rss.util.TorrentUtil - Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive; at path $
qb_ani-rss      | com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive; at path $
qb_ani-rss      |       at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1010)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:1227)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:1137)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:1047)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:982)
qb_ani-rss      |       at ani.rss.util.GsonStatic.fromJson(GsonStatic.java:23)
qb_ani-rss      |       at ani.rss.download.qBittorrent.lambda$getTorrentsInfos$2(qBittorrent.java:77)
qb_ani-rss      |       at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1078)
qb_ani-rss      |       at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
qb_ani-rss      |       at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
qb_ani-rss      |       at ani.rss.task.RenameTask.run(RenameTask.java:40)
```

## docker-compose
```
---
services:
  # 主要
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qb_qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=18080
      - TORRENTING_PORT=6881
      - QB_USERNAME=qusay
      - QB_PASSWORD="asdf;lkj "
    mem_limit: 2g
    volumes:
      # - /mnt/D1/Config/qbittorrent/config:/config
      - /mnt/D1/Data/qbittorrent/config:/config
      - /mnt/D1/Video:/mnt/D1/Video  #optional
      
    ports:
      - 18080:18080 # Web
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      bt_macvlan_network:  # 使用自定义 macvlan 网络 ip为172.16.1.202 ，作用为代理排除
      bt_network:          # 与 其他容器互通

  # 自动下载: 动漫|追番
  ani-rss:
    image: wushuo894/ani-rss
    container_name: qb_ani-rss
    volumes:
      - /mnt/D1/Data/ani-rss:/config
      - /mnt/D1/Video:/mnt/D1/Video  #optional
    ports:
      - 7789:7789
    environment:
      - PORT=7789
      - CONFIG=/config
      - TZ=Asia/Shanghai
    restart: always
    mem_limit: 2g
    networks:
      bt_network:

networks:  # 规避代理
  bt_macvlan_network:  # 定义 macvlan 网络
    driver: macvlan
    driver_opts:
      parent: ens18  # 替换为主机实际的物理网络接口名称
    ipam:
      config:
        - subnet: 172.16.1.0/24      # 替换为实际子网
          gateway: 172.16.1.1        # 替换为网关地址
          ip_range: 172.16.1.202/32  # 分配的 IP 地址范围
  bt_network:  # 容器内部通信
    driver: bridge
```

**Comment by wushuo894** [comment]
qb返回的数据存在问题，你更新一下qb容器试试

**Comment by w-66** [comment]
> qb返回的数据存在问题，你更新一下qb容器试试

删除了qb的config文件夹，重新启动容器，还是不行，
最后我直接删除了两个容器的config中的文件，依然还是不行
``` 
qb_ani-rss      | com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive; at path $
qb_ani-rss      |       at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1010)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:1227)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:1137)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:1047)
qb_ani-rss      |       at com.google.gson.Gson.fromJson(Gson.java:982)
qb_ani-rss      |       at ani.rss.util.GsonStatic.fromJson(GsonStatic.java:23)
qb_ani-rss      |       at ani.rss.download.qBittorrent.lambda$getTorrentsInfos$2(qBittorrent.java:77)
qb_ani-rss      |       at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1078)
qb_ani-rss      |       at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
qb_ani-rss      |       at ani.rss.download.qBittorrent.download(qBittorrent.java:182)
qb_ani-rss      |       at ani.rss.util.TorrentUtil.download(TorrentUtil.java:629)
qb_ani-rss      |       at ani.rss.util.TorrentUtil.downloadAni(TorrentUtil.java:198)
qb_ani-rss      |       at ani.rss.action.AniAction.lambda$post$5(AniAction.java:123)
qb_ani-rss      |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
qb_ani-rss      |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
qb_ani-rss      |       at java.base/java.lang.Thread.run(Unknown Source)
``` 

[20241128_qbittorrent.log](https://github.com/user-attachments/files/17950107/20241128_qbittorrent.log)
[20241128_ani-rss.log](https://github.com/user-attachments/files/17950108/20241128_ani-rss.log)

**Comment by wushuo894** [comment]
现有的日志不明确，这样吧。你拉这个镜像 wushuo894/ani-rss:test 再看看日志

**Comment by wushuo894** [comment]
<img width="452" alt="image" src="https://github.com/user-attachments/assets/812e82af-f6df-4b3d-bbd9-411c6050b836">

qb的响应，被禁止了

**Comment by wushuo894** [comment]
> <img alt="image" width="452" src="https://private-user-images.githubusercontent.com/46311469/390861194-812e82af-f6df-4b3d-bbd9-411c6050b836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTI4NzEsIm5iZiI6MTczMjgxMjU3MSwicGF0aCI6Ii80NjMxMTQ2OS8zOTA4NjExOTQtODEyZTgyYWYtZjZkZi00YjNkLWJiZDktNDExYzYwNTBiODM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE2NDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2M5MDc2OWQ0MWVlNTMyYTgzZWFkYTNlMmNlYmY1NjQyN2FhMWU3MTY5N2RhZDc3NTlhZjBjMjUzNDkzMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DhWyZrGYM8OO9nDoGshWVmVOtonvP05pvxHokH_pNTM">
> qb的响应，被禁止了

Forbidden

**Comment by wushuo894** [comment]
估计你的一些安全设置导致的

**Comment by w-66** [comment]
> 估计你的一些安全设置导致的

好吧，谢谢，我想想😂

**Comment by w-66** [comment]
> 估计你的一些安全设置导致的

找到原因了，如果地址那一栏填 容器内部通信地址: **`http://qb_qbittorrent:18080`** 就会报错，且无法使用，填外部IP地址就没有问题。虽然在容器内部地址和端口是ok的。不知道是哪个安全策略导致的。CSRF?


![图片](https://github.com/user-attachments/assets/5265d3d5-7d8d-45e5-accf-1ee92522f13f)

```
root@7b13e0e680ed:/usr/app# wget --spider -S http://qb_qbittorrent:18080
Spider mode enabled. Check if remote file exists.
--2024-11-30 13:24:07--  http://qb_qbittorrent:18080/
Resolving qb_qbittorrent (qb_qbittorrent)... 172.22.0.2
Connecting to qb_qbittorrent (qb_qbittorrent)|172.22.0.2|:18080... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
```


贴一个ok的，docker-compose.yml

```
---
networks:  # 规避代理
  network_172_16_1_0_24:  # 定义 macvlan 网络
    driver: macvlan
    driver_opts:
      parent: ens18  # 替换为主机实际的物理网络接口名称
    ipam:
      config:
        - subnet: 172.16.1.0/24      # 替换为实际子网
          gateway: 172.16.1.1        # 替换为网关地址
          ip_range: 172.16.1.0/24  # 分配的 IP 地址范围
  # qb_network:  # 容器内部通信
  #   driver: bridge


services:

  ani-rss:
    image: wushuo894/ani-rss    #可能需要换国内镜像源
    container_name: qb_ani-rss
    networks:
      network_172_16_1_0_24:
        ipv4_address: 172.16.1.203  # 指定固定 IP 地址
    volumes:
      - /mnt/D1/Data/ani-rss:/config
      - /mnt/D1/Video:/mnt/D1/Video  #optional
    ports:
      - 7789:7789       #WebUI端口，左侧可随意更改
    environment:
      - PORT=7789
      - CONFIG=/config
      - TZ=Asia/Shanghai
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_healthy  # 仅在 qbittorrent 健康检查通过后才启动


  qbittorrent:
    image: linuxserver/qbittorrent:latest   #可能需要换国内镜像源
    container_name: qb_qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=18080      # 
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/D1/Data/qbittorrent/config:/config
      - /mnt/D1/Video:/mnt/D1/Video  #optional
    ports:
      - 18080:18080        #WebUI端口，左侧可随意更改
      - 6881:6881        #监听端口，不建议改
      - 6881:6881/udp    #监听端口，不建议改
    networks:
      network_172_16_1_0_24:
        ipv4_address: 172.16.1.202  # 指定固定 IP 地址
      # qb_network:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080"]  # 使用 curl 检查 WebUI 是否可用
      interval: 30s       # 每30秒检查一次
      retries: 3          # 如果连续3次失败，认为服务不可用
      start_period: 20s   # 服务启动后10秒开始检查
      timeout: 10s        # 每次健康检查超时设置为5秒
 ```
